"""FastAPI route for RAG-based question answering over stored PDF chunks.

POST /api/ask
    1. Embed the question using sentence-transformers
    2. Search Pinecone for the most similar chunks
    3. Send chunks + question to Gemini to generate a final answer
    4. Return: question, final answer, and the chunks used as context
"""

import sys
import os

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

# Ensure backend root is importable when uvicorn runs from backend/
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from utils.embedding import generate_embedding
from services.pinecone_service import search_similar_chunks
from services.gemini_service import get_gemini_answer

router = APIRouter()


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=2,
        description="The question to answer from the uploaded PDF.",
        examples=["What is backpropagation?"],
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of top Pinecone chunks to retrieve as context (1-20).",
    )


class ChunkResult(BaseModel):
    text: str          = Field(description="The matched chunk text used as context.")
    filename: str      = Field(description="Source document filename.")
    chunk_index: int   = Field(description="Position of this chunk in the document.")
    score: float       = Field(description="Cosine similarity score (0.0 - 1.0).")


class AskResponse(BaseModel):
    question: str              = Field(description="The original question asked.")
    answer: str                = Field(description="Final answer generated by Gemini.")
    context_chunks: list[ChunkResult] = Field(description="Chunks retrieved from Pinecone used as context.")


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------

@router.post("/ask", response_model=AskResponse, summary="RAG: Semantic search + Gemini answer")
async def ask_question(req: AskRequest):
    """Full RAG pipeline: embed question → search Pinecone → generate answer with Gemini.

    Steps:
        1. Generate a 384-dim embedding for the question.
        2. Query Pinecone for the top-k most similar stored chunks.
        3. Pass the retrieved chunks as context to Gemini.
        4. Return the final answer along with the source chunks.

    Args:
        req: AskRequest with `question` (required) and `top_k` (optional, default 5).

    Returns:
        AskResponse with question, Gemini-generated answer, and context chunks.
    """
    question = req.question.strip()
    print(f"\n{'='*55}")
    print(f"[ASK] Question: \"{question}\"")

    # ── Step 1: Embed the question ───────────────────────────────────────────
    try:
        query_embedding = generate_embedding(question)
        print(f"[ASK] Step 1 - Embedding generated (dim={len(query_embedding)})")
    except Exception as e:
        print(f"[ASK] Step 1 FAILED - Embedding error: {e}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate embedding for the question: {str(e)}",
        )

    # ── Step 2: Retrieve similar chunks from Pinecone ────────────────────────
    try:
        raw_results = search_similar_chunks(query_embedding, top_k=req.top_k)
        print(f"[ASK] Step 2 - Pinecone returned {len(raw_results)} chunk(s)")
        for i, r in enumerate(raw_results):
            print(f"         #{i+1}  score={r['score']:.4f}  file={r['filename']}  chunk={r['chunk_index']}")
    except Exception as e:
        print(f"[ASK] Step 2 FAILED - Pinecone error: {e}")
        raise HTTPException(
            status_code=503,
            detail=f"Semantic search failed: {str(e)}",
        )

    # ── Step 3: Build context and generate answer with Gemini ────────────────
    context_chunks = [ChunkResult(**r) for r in raw_results]

    if not raw_results:
        # No chunks found — return a meaningful answer without calling Gemini
        print("[ASK] Step 3 - No chunks found in Pinecone, skipping Gemini")
        return AskResponse(
            question=question,
            answer="The answer was not found in the uploaded document. Please make sure you have uploaded a PDF and try again.",
            context_chunks=[],
        )

    # Extract just the text for the Gemini prompt
    chunk_texts = [r["text"] for r in raw_results if r.get("text", "").strip()]

    try:
        final_answer = get_gemini_answer(question, chunk_texts)
        print(f"[ASK] Step 3 - Gemini answer generated ({len(final_answer)} chars)")
    except Exception as e:
        print(f"[ASK] Step 3 FAILED - Gemini error: {e}")
        final_answer = None

    # Fallback: if Gemini failed or isn't configured, return best chunk text
    if not final_answer:
        print("[ASK] Step 3 - Gemini unavailable, falling back to top chunk text")
        final_answer = (
            raw_results[0]["text"]
            if raw_results
            else "The answer was not found in the uploaded document."
        )

    print(f"[ASK] Done. Answer preview: \"{final_answer[:80]}...\"")
    print(f"{'='*55}\n")

    return AskResponse(
        question=question,
        answer=final_answer,
        context_chunks=context_chunks,
    )
